### ISSUE TITLE
Not able to initialise the application

### ISSUE THREAD

**Issue by dushyantRathore** [cometchat-go/javascript-chat-sdk#2]
I tried to implement the basic application initialisation and login step but I am getting the following error.

```C:\Modeling\Cometchat\node_modules\@cometchat-pro\chat\CometChat.js:1
(function (exports, require, module, __filename, __dirname) { !function(t,e){if("object"==typeof exports&&"object"==typeof module)module.exports=e(function(){try{return require("react-native")}catch(t){}}());else if("function"==typeof define&&define.amd)define(["react-na
tive"],e);else{var n="object"==typeof exports?e(function(){try{return require("react-native")}catch(t){}}()):e(t["react-native"]);for(var r in n)("object"==typeof exports?exports:t)[r]=n[r]}}(window,function(r){return function(n){var r={};function o(t){if(r[t])return r[t
].exports;var e=r[t]={i:t,l:!1,exports:{}};return n[t].call(e.exports,e,e.exports,o),e.l=!0,e.exports}return o.m=n,o.c=r,o.d=function(t,e,n){o.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:n})},o.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object
.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},o.t=function(e,t){if(1&t&&(e=o(e))

ReferenceError: window is not defined
    at Object.<anonymous> (C:\Modeling\Cometchat\node_modules\@cometchat-pro\chat\CometChat.js:1:464)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Modeling\Cometchat\test.js:2:19)
    at Module._compile (module.js:652:30)
```

I tried to run the following code using node: 

```
//Import CometChat
const CometChat = require('@cometchat-pro/chat').CometChat;

var appID = "MY_APPLICATION_ID";   //Get the appID from the dashboard

//Initialise the application
CometChat.init(appID).then(
  () => {
    console.log("Initialization completed successfully");
    // You can now call login function.
  },
  error => {
    console.log("Initialization failed with error:", error);
    // Check the reason for error and take appropriate action.
  }
);
```

**Comment by anantgarg** [comment]
@dushyantRathore are you running this in a browser?

**Comment by anantgarg** [comment]
Please create a Github issue here: https://github.com/cometchat-pro/javascript-chat-sdk/issues
